version: '3.7'

services:
  app-server-new:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    expose:
      - '8080'
    depends_on:
      - mysql
    restart: always
    networks:
      - extras


  mysql:
    build:
      context: src/main/resources/static/MySQLDock
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: extras
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - extras

networks:
  extras:
    driver: bridge

volumes:
  mysql-db: