version: '3.7'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: extras
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - extras

networks:
  extras:
    name: extras
    driver: bridge

volumes:
  mysql-db: 